### ISSUE TITLE
出现报错Unexpected exception NVRTC error: NVRTC_ERROR_COMPILATION

### ISSUE THREAD

**Issue by Doctor-L-end** [jws92/YOLOv8-TensorRT#1]
![QQ20231225-161634](https://github.com/jws92/YOLOv8-TensorRT/assets/119040476/443086c5-4644-4d71-b041-e21eab49c9e3)

[ERROR] Exception caught in write_calibration_cache(): FileNotFoundError: [Errno 2] No such file or directory: ''

At:
  /home/hitcrt/yolov8_robomaster/YOLOv8-TensorRT-master/src/calibrator.py(148): write_calibration_cache
  /home/hitcrt/yolov8_robomaster/YOLOv8-TensorRT-master/src/onnx2trt.py(107): convert_trt_engine
  /home/hitcrt/yolov8_robomaster/YOLOv8-TensorRT-master/src/onnx2trt.py(134): main
  /home/hitcrt/yolov8_robomaster/YOLOv8-TensorRT-master/src/onnx2trt.py(138): <module>

[12/25/2023-16:09:38] [TRT] [W] Missing scale and zero-point for tensor /model.30/dfl/Softmax_output_0, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[12/25/2023-16:09:38] [TRT] [W] Missing scale and zero-point for tensor (Unnamed Layer* 352) [Constant]_output, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
activation(42): error: identifier "inff" is undefined
      dst0 = tmp * inff;
                   ^

1 error detected in the compilation of "activation".

[12/25/2023-16:14:05] [TRT] [E] 1: Unexpected exception NVRTC error: NVRTC_ERROR_COMPILATION
Failed to building TRT engine!

**Comment by jws92** [comment]
Umm.. Did you set '--calib_cache' argument?

**Comment by Doctor-L-end** [comment]
no, I can not find a calib_cache

**Comment by Doctor-L-end** [comment]
I only set "--calib_img_path" argument

**Comment by jws92** [comment]
Ah, you should set '--calib_cache' even if you don't have. 
The calibration cache file is automatically generated when running the code.

**Comment by Doctor-L-end** [comment]
![QQ20231225-163835_2](https://github.com/jws92/YOLOv8-TensorRT/assets/119040476/8aadcb37-d777-411c-a701-7fee4ae90a61)

**Comment by jws92** [comment]
Umm... I am sorry but I did not encounter that errors when converting official YOLOv8 weights with COCO validation dataset.
What kind of the model do you use?

**Comment by Doctor-L-end** [comment]
the model is yolov8n-seg

**Comment by jws92** [comment]
I just only tested detection model, so I will check the segmentation model.

**Comment by Doctor-L-end** [comment]
Okay, I succeeded. This error should be because the ONNX model I used before was generated from another computer. I just used the ONNX model generated from my own computer, and now there is no error.

**Comment by jws92** [comment]
I just got YOLOv8n-seg weights with COCO dataset, and I converted the INT8 engine without any problems.
As you mentioned it, I think you just newly convert torch model to ONNX, then you can get INT8 engine successfully.

In this repo, I only coded postprocess module for detection, so you should modify the code with addtional postprocess module for segmentation if you want to get segmentation results.

**Comment by Doctor-L-end** [comment]
okay, thank you
